version: 2.1

common: &common
  steps:
    - checkout
    - run:
        name: Prepare submodules
        command: git submodule sync
    - run:
        name: Checkout submodules
        command: git submodule update --init
    - run:
        name: Build V8
        command: ./build-v8.sh macOS v7.8.279.23

jobs:
  build-linux:
    machine:
      image: ubuntu-1604:201903-01
    <<: *common
  build-osx:
    macos:
      xcode: 11.2.1
    <<: *common

workflows:
  version: 2
  build:
    jobs:
      - build-linux
      - build-osx
