trigger:
  - master

jobs:
  - job: build
    strategy:
      matrix:
        linux:
          platform: Linux
          imageName: ubuntu-latest
        macos:
          platform: macOS
          imageName: macOS-latest
    displayName: "Build V8 for ${{ variables.platform }}"
    pool:
      vmImage: "$(imageName)"
    steps:
      - checkout: self
        fetchDepth: 1
        submodules: true
      - task: Cache@2
        inputs:
          key: 'v8-cache | "$(Agent.OS)"'
          restoreKeys: v8-cache | "$(Agent.OS)"
          path: v8
        displayName: Cache V8
      - script: ./build-v8.sh $(platform) v7.8.279.23
        displayName: Build V8
