trigger:
  - master

jobs:
  - job: build
    strategy:
      matrix:
        linux:
          platform: Linux
          imageName: ubuntu-latest
        macos:
          platform: macOS
          imageName: macOS-latest
    displayName: Build V8 for $(platform)
    pool:
      vmImage: "$(imageName)"
    steps:
      - checkout: self
        fetchDepth: 1
        submodules: true
      - script: ./build-v8.sh $(platform) v7.8.279.23
        displayName: Build V8
