name: Build

on:
  push:
    branches-ignore:
      - "refs/tags/**"

jobs:
  build:
    name: Build V8 using ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Build V8 v7.8.279.23
        id: build
        run: ./build-v8.sh ${{ runner.os }} v7.8.279.23

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: "${{ steps.build.outputs.package }}"
          path: package
