name: Release

on:
  release:
    types: [created]

jobs:
  release:
    name: Build V8 for release using ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: "${{ matrix.os }}"
    steps:
      - name: Show event
        run: cat "$GITHUB_EVENT_PATH" | jq -M .

      - name: Checkout
        uses: actions/checkout@v1
        with:
          fetch-depth: 1
          submodules: true

      - name: Build V8
        id: build
        run: ./build-v8.sh ${{ runner.os }} ${{ github.ref }}

      - name: Upload artifact
        uses: actions/upload-artifact@v1
        with:
          name: "${{ steps.build.outputs.package }}"
          path: package

      - name: Upload release
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
        with:
          upload_url: "${{ github.event.upload_url }}"
          asset_path: "${{ steps.build.outputs.package_path }}"
          asset_name: "${{ steps.build.outputs.package }}.tar.gz"
          asset_content_type: application/gzip
